### ISSUE TITLE
Generated class order should reflect source

### ISSUE THREAD

**Issue by marcandre** [ruby/typeprof#18]
For some reason, `typeprof` on `lib/matrix` generates rbs for `Matrix`, then `Vector`, but if I provide a hint file below, then the order is reversed, `Vector` first then `Matrix`:

```ruby
type numeric = Integer | Float | Rational | Complex

class Matrix
  @rows : Array[Array[numeric]]
end

class Vector
  @elements : Array[numeric]
end
```

**Comment by mame** [comment]
The order was reversed due to topological sort of classes declared in RBS (to process a superclass earlier, a subclass later).

Now, TypeProf outputs `Matrix`, `Vector`, and `ExceptionForMatrix`. This is because TypeProf defines `Matrix` and `Vector` based on matrix.rbs, and then defines `ExceptionForMatrix` based on lib/matrix.rb. I'm unsure if this is the best order, but this is where things are currently.

```
$ time bundle exec exe/typeprof ../ruby/lib/matrix.rb matrix.rbs
# Classes
class Matrix
  ...
end

class Vector
 ...
end

module ExceptionForMatrix
  ...
end

real    0m6.422s
user    0m6.322s
sys     0m0.091s
```

BTW, I've investigated the performance bottleneck in analysis of matrix.rb, and found [a heavy but useless calculation](https://github.com/ruby/typeprof/commit/bff9a81f5dbb0de6778cb2ed3340340757474a50). By removing it, now the analysis takes about a few seconds. (But note that it may become longer again in future by further precision improvement.)

**Comment by marcandre** [comment]
> Now, TypeProf outputs Matrix, Vector, and ExceptionForMatrix. This is because TypeProf defines Matrix and Vector based on matrix.rbs, and then defines ExceptionForMatrix based on lib/matrix.rb. I'm unsure if this is the best order

Sounds perfect! 👍
